image: node:alpine
before_script:
  - npm install npm -g
  - npm ci

stages:
  - test

unit-test-job:
  stage: test
  tags:
    - hetzner
  script:
    - 'jest --ci --reporters=default --reporters=jest-junit'
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
