image: node:alpine
before_script:
  - npm install npm -g
  - npm ci

stages:
  - test

unit-test-job:
  stage: test
  before_script:
    - npm install npm -g --prefer-offline
  script:
    - echo "Running unit tests"
    - npm run test:push
