image: node:alpine
before_script:
  - npm install npm -g --prefer-offline
  - npm ci

stages:
  - test

unit-test-job:
  stage: test
  tags:
    - hetzner
  script:
    - npx jest --v
    - npx jest --ci
